# Generated by Django 2.2.3 on 2019-07-09 10:22

from django.db import migrations
from django.contrib.auth.models import User
from ..models import Account

def create_accounts(apps, schema_editor):
    for user in User.objects.all():
        if not user.account:
            account = Account.objects.create()
            user.account = account
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
    ]
